### PR TITLE
use string instead of bool value in docker-copose environment

### PR DESCRIPTION
**Pull request by superbjorn09**
services.satisfactory-server.environment.ROOTLESS contains false, which is an invalid type, it should be a string, number, or a null
services.satisfactory-server.environment.STEAMBETA contains false, which is an invalid type, it should be a string, number, or a null

### CODE REVIEW

**Comment by wolveix** [comment]
Are you experiencing this as an issue on your end? Docker compose has no issues with these

**Comment by superbjorn09** [comment]
Its probably just a compatibility thingi, cause I use a rather old version of docker-compose:
docker-compose version 1.25.0

making this a string "should" make it work on older and newer version, but you better double check if the params get applied correctly if you re using a newer version of docker-compose

**Comment by DenuxPlays** [comment]
I think yaml does not known the difference between strings and bool or am I wrong?

**Comment by skupfer** [comment]
It should be a string as `false` is a special token in yaml, namely `boolean`. The application which interprets yaml will handle it. https://devops.stackexchange.com/a/542

**Comment by voruti** [comment]
This unfortunately isn't correct, you're mixing up things.

The `docker-compose.yml` at hand uses a list of environment variables:
```yml
    environment:
      - ROOTLESS='false'
      - STEAMBETA='false'
```
where the whole line is just a YAML string (everything behine the "- ").

On the contrary there also are environment variables as YAML objects/keys:
```yml
    environment:
      ROOTLESS: "false"
      STEAMBETA: "false"
```
where there are YAML key-value relations.
> It should be a string as `false` is a special token in yaml, namely `boolean`.

This is where that applies and "false" must be put into quotes.

Generally speaking, Docker can handle both variants.
But: putting quotes around "false" while using the first variant is wrong. In that case, the quotes are picked up literally and get put into the environment variable itself.

The command `docker compose config` allows to see a summary of the configuration. The output of that command for the `docker-compose.yml` _introduced by this PR_ is the following (excerpt):
```yml
    environment:
      ROOTLESS: '''false'''
      STEAMBETA: '''false'''
```
(wrongly escaped boolean strings)

_Prior to the PR_ it was:
```yml
    environment:
      ROOTLESS: "false"
      STEAMBETA: "false"
```
Here Docker automatically parsed the first variant (where the whole line is a single string) and output the configuration in the format of the second variant (with correctly escaped "false").

**Comment by skupfer** [comment]
Thanks for your reply @voruti and proving my point that it does make a difference.

As I only replied to Denux on the matter I didn't check the commit properly as I have seen the `key:value` format here before. I think I mixed it up here https://github.com/wolveix/satisfactory-server/commit/82797b5c36b9d9c893d042e37f49d7fc27f28197 but only the readme got adjusted. My bad.

**Comment by wolveix** [comment]
Thanks for the correction @voruti. That's what I thought I remembered, but I hastily merged this while dealing with other 1.0 things. It was only in the docker-compose.yml file, while most people copy from the README :) My apologies for not reviewing this properly myself

**Pull request merged**
