### PR TITLE
Improved `docker run` command

### PR DESCRIPTION
**Pull request by DenuxPlays**
* made it more readable by separating options
* replaced `-d` (detached) with `--sig-proxy=false`
    * shows the logs -> easier to debug problems
    * exit with ctrl + c without stopping the container
* replaced `-h` with `--hostname` to clarify the option
* reordered options to move up the important ones
* added `--restart unless-stopped`

### CODE REVIEW

**Comment by wolveix** [comment]
Hey! Thanks for taking the time to open this PR :) I do believe there is value in your contributions; however, I think I'd decline merging them in their current state.

While I agree that this is easier to read for those of us that are familiar with a command line, from my own experience, I fear that many people will misunderstand that this is a single command (you'd be surprised). On the same note, I suspect that the added verbosity would only confuse people that don't frequent this industry. While `-d` is very common among other open-source repos, `--sig-proxy` isn't. I don't really use it myself, yet I use Docker on a near-daily basis in both personal and professional contexts. The current order of the arguments is intentional for a similar reason; to appear familiar to most users who may have experience with similar repos.

`--restart unless-stopped` is the one thing that I do believe should be there by default, I'm surprised I somehow omitted it when I initially created the repo! Please do argue with any of my points if you disagree, I'd welcome your perspective!

**Comment by DenuxPlays** [comment]
I'll get why you would prefer `-d` over `--sig-proxy` and I think its a matter of opinion, so I'm fine with going back to `-d`.
One think I would add is an explanation of the command, so I'll do this later.

My explanation for the reorder is:
* kept important things like name, hostname and restart policy at the start
* in the middle their are options that have to be edited or are most likely to
* finally their are options like memory-reservation and ports that should only be edited if you know what you are doing

I'll rework this PR (probably tomorrow) based on your feedback.

**Comment by DenuxPlays** [comment]
Will finish this soon
Hopefully this week.

**Comment by psych0d0g** [comment]
for the sake of readability i would suggest of not using the short hand flags in scripts.
personally i would prefer them written out as long as you are not using them on a interactive shell session.
for example:
`--volume` instead of `-v`
`--env` instead of `-e`

**Comment by wolveix** [comment]
@DenuxPlays any updates on this?

**Comment by DenuxPlays** [comment]
> @DenuxPlays any updates on this?

Nope sorry...
totally forgot about this pr 
I'll finish this quick

**Comment by DenuxPlays** [comment]
@wolveix Finished (I think)
Hopefully I missed nothing.
Take a look and leave a review so I can improve some things if necessary.

**Pull request merged**
