### PR TITLE
Satisfactory 1.0 Port changes

### PR DESCRIPTION
**Pull request by ikiris**
I think I got all the places that 1.0 changes its port formats to just udp/tcp 7777. Will send over more fixes if I run into more things tomorrow when the release happens.

### CODE REVIEW

**Comment by Sleavely** [comment]
Nicely done. For reviewers reference: the port change to exclusively use TCP+UDP on 7777 was announced in [this video](https://youtu.be/v8piXNQwcUw?t=232) at 3:53.

**Review by thijsvanloef — CHANGES_REQUESTED** [review]
Keep in mind that the following would also need to be changed once the 1.0 update hits live: https://github.com/wolveix/satisfactory-server/blob/df2817f873401170aff722229414a589077e9c42/run.sh#L188

**Comment by wolveix** [comment]
I've pre-updated the README on [DockerHub](https://hub.docker.com/r/wolveix/satisfactory-server/). Honestly we're probably fine to merge this now, but I'll hold off until an hour before launch.

**Comment by DenuxPlays** [comment]
@wolveix Will there be a new release (v2.0 or so?) when this will be merged or do I have to use the dev tag?

**Comment by wolveix** [comment]
@DenuxPlays yeah, I'll add a new release. It'll probably be `1.7`, though it'll also be pushed to `latest` and `dev` :)

**Pull request merged**
