### PR TITLE
K8s Resource Manifests

### PR DESCRIPTION
**Pull request by mitchellmaler**
Here is my resource manifests I am using to deploy this image. Please let me know if I should update anytime.

### CODE REVIEW

**Review by sadortun — APPROVED** [review]
Excellent !

**Comment by sadortun** [comment]
Maybe you could add a note in the readme ?

**Comment by wolveix** [comment]
Brilliant, thanks for your contribution!

Just a few things that I'd like to add prior to merging this. I believe some information should be added to the `README` per @sadortun's suggestion. In addition to this, it'd be nice if you could include an `ingress.yml` declaration too :)

**Comment by mitchellmaler** [comment]
I can definitely add something about this in the README but I don't think an ingress resource will be applicable here. Since this service requires UDP and specific open ports then an ingress won't usually be used here or if so would be a advanced setup. Using just a Service with NodePort or LoadBalancer (if provider supports UDP) would be the right approach.

**Comment by mitchellmaler** [comment]
I started working on a helm chart for this instead of just static resource manifests. This should make it easier to deploy and allow for different configurations.

**Pull request merged**
